#!/usr/bin/perl -eexec {'/usr/bin/python'} ('/usr/bin/perl', '-B', @ARGV)
# See, it's technically still a perl script, right?
# See! Even vim thinks so!
# vim: filetype=python

import os
_DIR_NAME = os.path.dirname(os.path.abspath(__file__))
_SCRIPT_NAME = os.path.splitext(os.path.basename(__file__))[0]

import sys
sys.path = [os.path.join(_DIR_NAME, "pylib")] + sys.path

import datetime
import dateutil.parser
import glob
import libxml2
import logging
import optparse
import pytz
import re

from feedgen.feed import FeedGenerator

_DEFAULT_EMAIL = 'nospam@nlnc.org'


class BadXML(Exception):
    pass


def _main(argv):
    options, dirs = _parse_args(argv)
    _setup_logging(options.verbose)
    if len(dirs) == 0:
        logging.critical("You must specify at least one DIR.")
        return 1

    now = pytz.utc.localize(datetime.datetime.utcnow())
    fg = FeedGenerator()
    fg.load_extension('podcast')
    fg.podcast.itunes_category('Religion & Spirituality', 'Christianity')
    fg.title(options.title)
    fg.description(options.description)
    fg.link(href=options.link)
    fg.pubDate(now)
    fg.updated(now)
    fg.podcast.itunes_explicit('clean')
    fg.podcast.itunes_author('nlnc.org')
    fg.ttl(60)

    for d in dirs:
        _process_dir(d, fg)

    if options.output == '-':
        fd = sys.stdout
    else:
        fd = open(options.output, 'w')

    fd.write(fg.rss_str(pretty=True, encoding='UTF-8'))


def _process_dir(d, fg):
    g = os.path.join(d, "*.m3u")
    logging.debug("Looking in %s", g)
    items = []
    for m3u in sorted(glob.glob(g), reverse=True):
        logging.debug("    %s", m3u)
        try:
            _add_rss_item(m3u, fg)
        except Exception as exc:
            logging.error("Could not add %s: %s", m3u, exc)
    return items


def _add_rss_item(m3u, fg):
    data = _process_m3u(m3u)
    text = data.get('text', "")
    lect = data.get('lect', "")
    desc = []
    if text:
        desc.append("Text: %s" % text)
    if lect:
        desc.append("Lectionary: %s" % lect)
    desc = ", ".join(desc)
    link = data['link']
    fe = fg.add_entry()
    fe.description(desc)
    fe.title(data['title'])
    fe.podcast.itunes_explicit('clean')
    fe.enclosure(link, 0, 'audio/mpeg')
    fe.pubdate(data['date'])
    fe.id(link)
    fe.podcast.itunes_author(data['speaker'])


def _process_m3u(m3u):
    assert(m3u.endswith('.m3u'))
    xml = re.sub(r'.m3u$', '.xml', m3u)
    logging.debug("    %s", xml)
    data = _process_xml(xml)
    with open(m3u) as fd:
        data['link'] = fd.readline().rstrip()
    return data


def _process_xml(xml):
    ret = {}
    doc = libxml2.parseFile(xml)
    # more /home/www/html/recordings/English/20140427.xml
    # <recording>
    # <link>20140427.m3u</link>
    # <date>2014/04/27</date>
    # <speaker>Jeff Purganan</speaker>
    # <title>Speak Peace to Someone</title>
    # <text></text>
    # <lect></lect>
    # <notes></notes>
    # <slides></slides>
    # </recording>
    recording = _get_el(doc, "recording", xml)
    if recording is None:
        raise BadXML("<recording> not found.")
    for n in ("title", "link", "date", "speaker", "text", "lect", "notes", "slides"):
        node = _get_el(recording, n, xml)
        if node is not None:
            ret[n] = node.content
    date = ret.get("date", None)
    if date is None:
        raise BadXML("<date> missing in %s" % xml)
    try:
        date = dateutil.parser.parse(date)
        date = pytz.timezone('America/Los_Angeles').localize(date)
        ret['date'] = date
    except Exception as exc:
        raise BadXML("bad <date> format in %s: %s" % (exc, xml))
    return ret


def _get_el(r, el, xml):
    res = r.xpathEval("%s" % el)
    if len(res) == 0:
        return None
    if len(res) > 1:
        raise BadXML("Too many <%s> elements not found in %s." % (el, xml))
    return res[0]


def _parse_args(argv):
    parser = optparse.OptionParser()
    parser.add_option('-v', '--verbose', help="Turn on verbose.", action="store_true", default=False)
    parser.add_option('-t', '--title', help="Title of RSS feed")
    parser.add_option('-d', '--description', help="Description of RSS feed")
    parser.add_option('-l', '--link', help="Link to content page")
    parser.add_option('-o', '--output', help="Output", default='-')
    options, dirs = parser.parse_args(args=argv)
    if options.title is None:
        parser.error("--title is required.")
    if options.description is None:
        parser.error("--description is required.")
    return options, dirs


def _setup_logging(verbose):
    lvl = logging.DEBUG if verbose else logging.INFO
    fmt = _SCRIPT_NAME + ': %(levelname)s%(message)s'
    logging.basicConfig(level=lvl, format=fmt)
    logging.addLevelName(logging.DEBUG, 'debug: ')
    logging.addLevelName(logging.INFO, '')
    logging.addLevelName(logging.WARNING, 'warning: ')
    logging.addLevelName(logging.ERROR, 'error: ')
    logging.addLevelName(logging.CRITICAL, 'critical: ')


if __name__ == '__main__':
    try:
        sys.exit(_main(sys.argv[1:]))
    except KeyboardInterrupt:
        print >> sys.stderr, '%s: interrupted' % _SCRIPT_NAME
        sys.exit(130)
