#!/usr/bin/perl

use strict;
use warnings;

my $BG_COLOR = "#ffcc99";
my $HEADING_COLOR = "#cc6600";
my $LINK_COLOR = $HEADING_COLOR; #"#000000"; # "#cc6600"
my $LINK_COLOR_HOVER = "#551A8B"; 
my $LINK_COLOR_VISITED = $LINK_COLOR; #"#000000";

use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Quotekeys = 0;

sub d {
    my $text = Dumper(@_);
    1 while $text =~ s/(.*)^([^\n]*)bless\( \{\n(.*?)^(\s*\}), '([^']*)' \)([^\n]*)/$1$2$5 {\n$3$4$6 # $5/ms;
    $text =~ s/IXM3U:://g;
    warn $text;
};

my $DEBUG = 0;
use XML::Parser;

my $p1 = new XML::Parser(Style => 'Objects', Pkg => "IXM3U");

#<body background="../../snbrst.jpg">
my @files = reverse sort <*.m3u>;
print <<END;
<html>
<body style="background-color: $BG_COLOR">
<style>
a:hover   { color:$LINK_COLOR_HOVER; }
a:visited { color:$LINK_COLOR_VISITED; }
a         { color:$LINK_COLOR; }
h2	  { color:$HEADING_COLOR; }
</style>
<img src=http://www.nlnc.org/_/rsrc/1236035577943/config/app/images/customLogo/customLogo.gif/>
<h2><i>Recent Recordings</i></h2>
(click on date for lectionary readings, title to listen, [mp3] to access mp3 file directly)
<big>
END

for my $m3u (@files) {
    (my $xml = $m3u) =~ s/m3u$/xml/;
    if (-e $xml) {
	%::chars = ();
	my $root = $p1->parsefile($xml);
	print $root->[0]->html();
	next;
    }
}
print "</big>\n";
print "</body>\n";
print "</html>\n";

package IXM3U::Characters;

sub collect {
    my $self = shift;
    my $text = $self->{Text};
    $text =~ s/\n/ /g;
    $text =~ s/^ +//;
    $text =~ s/ +$//;
    $::chars{$::collect} .= $text;
    return "";
}

package IXM3U::recording;

sub html {
    my $self = shift;
    $::collect = "html";
    my $html = "<p>\n";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
    my $date = $::chars{date};
    my $link = $::chars{link};
    my $title = $::chars{title};
    my $speaker = $::chars{speaker};
    my $text = $::chars{text};
    my $lect = $::chars{lect};
    my $notes = $::chars{notes};
    my $slides = $::chars{slides};

    my $week = $date;
    $week =~ s/\/0*/-/g;
    $week =~ s/ //g;
    my $lectlink = "lect/cur/wide/html/weeks/WK$week.html";

    if (-e "/home/gloria/public_html/$lectlink") {
	$date = " <a href='http://www.wall.org/~gloria/$lectlink'>$week</a>";
    }
    else {
	warn $lectlink;
    }
    $link =~ s/ +$//;
    #### RJR 1/2008 BEGIN
    my $mp3_rjr;
    if (defined $link && length $link) {
       $mp3_rjr = $link;
       $mp3_rjr =~ s/\.m3u$/.mp3/g;
       $mp3_rjr = '_mp3_' . '/' . $mp3_rjr;
       if ( -e $mp3_rjr ) {
          $mp3_rjr = "<a href=\"$mp3_rjr\">[mp3]</a>";
       } else {
          $mp3_rjr = "";
       }
    }
    #### RJR 1/2008 END
    $html .= <<"END";
    $date: &nbsp; <a href="$link"><i>$title</i></a>, $mp3_rjr, $speaker<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$text
END
    if ($::chars{lect} =~ /\S/) {
	$html .= " ($lect)";
    }
    if ($::chars{notes} =~ /\S/) {
	$notes =~ s/ +$//;
	$html .= " <a href=\"$notes\"><i>(lecture notes)</i></a>";
    }
    if ($::chars{slides} =~ /\S/) {
        $slides =~ s/ +$//;
	$html .= " <a href=\"$slides\"><i>(slides)</i></a>";
    }
    $html .= "</p>\n";
}

package IXM3U::link;

sub collect {
    my $self = shift;
    $::collect = "link";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::date;

sub collect {
    my $self = shift;
    $::collect = "date";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::speaker;

sub collect {
    my $self = shift;
    $::collect = "speaker";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::title;

sub collect {
    my $self = shift;
    $::collect = "title";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::text;

sub collect {
    my $self = shift;
    $::collect = "text";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::lect;

sub collect {
    my $self = shift;
    $::collect = "lect";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::notes;

sub collect {
    my $self = shift;
    $::collect = "notes";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}

package IXM3U::slides;

sub collect {
    my $self = shift;
    $::collect = "slides";
    foreach my $kid (@{$$self{Kids}}) {
	$kid->collect();
    }
}
